name: Build

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-sha-${{ github.sha }}

permissions: read-all

jobs:
  changes:
    name: Change detection
    runs-on: ubuntu-latest
    outputs:
      kt: ${{ steps.changes.outputs.kt }}
      misc: ${{ steps.changes.outputs.misc }}
    steps:
      - name: Check out repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            kt:
              - '**/*.{kt,properties}'
              - '**/*gradle*'
              - '**/resources/**'

  build:
    name: Build
    needs: changes
    if: ${{ needs.changes.outputs.kt }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Merge with target branch
        if: ${{ contains(github.event_name, 'pull_request') }}
        uses: check-spelling/checkout-merge@main

      - name: Set up Eclipse Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --no-daemon shadowJar
