name: Codacy Security Scan

on:
  pull_request:
    branches: [main]

  schedule:
    - cron: "29 9 * * 6"

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-sha-${{ github.sha }}

permissions:
  contents: read

jobs:
  changes:
    name: Change detection
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - name: Check out repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - '**/*.kt'
              - '**/*.kts'
              - '**/*.properties'
              - '**/resources/*.xml'
              - 'gradle*'

  codacy-security-scan:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    permissions:
      # for actions/checkout to fetch code
      contents: read
      # for github/codeql-action/upload-sarif to upload SARIF results
      security-events: write
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@09916000460adeeedc96b9704f86deba53e2ad5d
        with:
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
