name: Documentation

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      manual:
        default: "1"
        description: "Manual"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-sha-${{ github.sha }}

permissions: read-all

jobs:
  changes:
    name: Change detection
    runs-on: ubuntu-latest
    outputs:
      kt: ${{ steps.changes.outputs.kt }}
      misc: ${{ steps.changes.outputs.misc }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - '**/*.{kt,properties}'
              - '**/*.md'
              - '**/*gradle*'

  build:
    name: Documentation
    needs: changes
    if: |
      github.event.inputs.manual != '' ||
      needs.changes.outputs.src == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Eclipse Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Dokka
        run: ./gradlew --no-daemon dokkaHtmlMultiModule

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokka/htmlMultiModule/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
