name: Test

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-sha-${{ github.sha }}

jobs:
  changes:
    name: Change detection
    runs-on: ubuntu-latest
    outputs:
      kt: ${{ steps.changes.outputs.kt }}
      misc: ${{ steps.changes.outputs.misc }}
    steps:
      - name: Check out repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            kt:
              - '**/*.{kt,properties}'
              - '**/*gradle*'
              - '**/resources/**'

            misc:
              - '**/*.{js,json,md,sh,xml,yaml,yml}'

  test:
    name: Test
    needs: changes
    if: ${{ needs.changes.outputs.kt }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Merge with target branch
        if: ${{ contains(github.event_name, 'pull_request') }}
        uses: check-spelling/checkout-merge@main

      - name: Set up Eclipse Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon :allTestAggregateTestReport

      - name: Setup Testspace client
        uses: testspace-com/setup-testspace@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          domain: ${{ github.repository_owner }}

      - name: Publish results to Testspace
        if: ${{ github.ref == 'refs/heads/main' }}
        run: testspace **/build/test-results/allTest/*.xml

      - name: Coverage report
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon :allTestCodeCoverageReportMarkdown

      - name: Get markdown report contents
        id: markdown-report
        run: |
          echo "contents<<EOF
          <h3>Test coverage</h3>

          $(
            cat \
              "build/reports/jacoco/allTestCodeCoverageReport/allTestCodeCoverageReport.md"
          )
          EOF" >> $GITHUB_OUTPUT

      - name: Add coverage to PR
        if: ${{ contains(github.event_name, 'pull_request') }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ steps.markdown-report.outputs.contents }}
          pr_number: ${{ github.event.issue.number }}

      - name: Add coverage to job summary
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<EOF
          <h3>Test coverage</h3>

          $(
            cat \
              build/reports/jacoco/allTestCodeCoverageReport/allTestCodeCoverageReport.md
          )
          EOF

      - name: Upload coverage to Coveralls
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: coverallsapp/github-action@v2
        with:
          base-path: src/main/kotlin
          file: ${{ github.workspace }}/build/reports/jacoco/allTestCodeCoverageReport/allTestCodeCoverageReport.xml
          format: jacoco
